### ISSUE TITLE
Do you have any out of the box php chunking classes that would work this?

### ISSUE THREAD

**Issue by jackttcoms** [Buzut/huge-uploader#1]
Do you have any out of the box PHP chunking classes that would work this? Also would your js work for my needs of having a form with [textarea, fileinput1, fileinput2, fileinput3, submit]?

Thanks in advance

**Comment by Buzut** [comment]
Hi,
Sorry for the late answer. 
* No I don't have anything PHP, but would be willing to link to a repo built for that purpose if you do so.
* The code would definitely work for your need, that's what it was build for.
