### ISSUE TITLE
Problem on IE11

### ISSUE THREAD

**Issue by Jaffsterz** [Buzut/huge-uploader#10]
Even when polyfilling Fetch and Promise, we can't get this to work on IE11.

We get the same issue as reported here, due to the dependency on event-target-shim:

[https://github.com/mysticatea/event-target-shim/issues/30](https://github.com/mysticatea/event-target-shim/issues/30)

Maybe the dependency (3.0.1) is now too old to be supported?

Edited: we have fixed this by babel polyfilling node_modules/event-target-shim itself

**Comment by Buzut** [comment]
Hi @Jaffsterz,
Sorry for my late answer. I can't really test under IE11. 
Actually it seems that it's lower level and not directly an issue with my module's code.

I'm seeing the issue hasn't been resolved on event-target-shim if you have any other option, I'm all ears.

In the meantime, as I can't directly do anything, I'm closing the issue.
